name: New feature
description: Add a new feature
title: "[ Feature ]  "
projects: ["can-i-take-over-this-subdomain"]
assignees:
  - pdelteil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time!
  - type: dropdown
    id: type
    attributes:
      label: Priority
      description: How fast do you need it?
      options:
        - High
        - Medium
        - Low
      default: 2
    validations:
      required: true
  - type: textarea
    id: fingerprint
    attributes:
      label: Fingerprint
      description: Paste here the fingerprint used to identify this takeover
      placeholder: Site not found or NXDomain error      
    validations:
      required: true
      description: If there is already a nuclei template to detect this takeover, add the URL
      placeholder: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/takeovers/bitbucket-takeover.yaml
    validations:
      required: false  

