name: New feature
description: Add a new subdomain takeover case
title: "[Takeover]  "
labels: ["takeover"]
projects: ["can-i-take-over-this-subdomain"]
assignees:
  - pdelteil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share this new subdomain takeover!
  - type: input
    id: servicename
    attributes:
      label: Service name
      description: What's the name of the vulnerable service?
      placeholder: ex. Github
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type of detection
      description: Is it a NXDOMAIN error or a web error/message?
      options:
        - NXDOMAIN
        - Web Error
      default: 1
    validations:
      required: true
  - type: textarea
    id: fingerprint
    attributes:
      label: Fingerprint
      description: Paste here the fingerprint used to identify this takeover
      placeholder: Site not found or NXDomain error      
    validations:
      required: true
  - type: input
    id: nuclei
    attributes:
      label: Nuclei template?
      description: If there is already a nuclei template to detect this takeover, add the URL
      placeholder: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/takeovers/bitbucket-takeover.yaml
    validations:
      required: false  
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Add screenshots to prove the takeover


